server:
  port: 8088

logging:
  path: logs
  file: mylog.log

spring:
  application:
    name: Application
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/my_test?useSSL=true&amp;characterEncoding=utf-8;
    username: root
    password: root


mybatis:
  #用mybatis所对应必须的module，即java bean对应的包，java下对应的包
  type-aliases-package: com.autest.code
  #写sql的,对应resource下mapper文件夹下所有
  mapper-locations:
    - mapper/*